### ISSUE TITLE
Raspberry pi armhf maxReadMaxBytes isssue

### ISSUE THREAD

**Issue by Dam63** [connectrpc/connect-es#1249]
**Describe the bug**

I run my  program on my fat windows computer with no issue
I have try to migrate on raspberry pi 3.
After a dependencies conflict that lead me to disable @bufbuild/buf (arm not compatible but look ok for this project to remove it)

Finally it was running but got :
```
[00:00:01.636] [ERROR] ConnectError: [internal] decompression failed
    at /xxx/node_modules/@connectrpc/connect-node/dist/cjs/compression.js:78:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async envelopeDecompress (/xxx/node_modules/@connectrpc/connect/dist/cjs/protocol/envelope.js:115:16) {
  rawMessage: 'decompression failed',
  code: 13,
  metadata: HeadersList {
    cookies: null,
    [Symbol(headers map)]: Map(0) {},
    [Symbol(headers map sorted)]: null
  },
  details: [],
  cause: RangeError [ERR_OUT_OF_RANGE]: The value of "options.maxOutputLength" is out of range. It must be >= 1 and <= 1073741823. Received 4294967295
      at Gunzip.ZlibBase (node:zlib:278:23)
      at Gunzip.Zlib (node:zlib:695:3)
      at new Gunzip (node:zlib:759:3)
      at asyncBufferWrapper (node:zlib:800:23)
      at node:internal/util:375:7
      at new Promise (<anonymous>)
      at asyncBufferWrapper (node:internal/util:361:12)
      at Object.decompress (/xxx/node_modules/@connectrpc/connect-node/dist/cjs/compression.js:40:31)
      at envelopeDecompress (/xxx/node_modules/@connectrpc/connect/dist/cjs/protocol/envelope.js:115:34)
      at /xxx/node_modules/@connectrpc/connect/dist/cjs/protocol/async-iterable.js:507:92 {
    code: 'ERR_OUT_OF_RANGE'
  }
}
```

I have edit 
 - ./node_modules/@connectrpc/connect/dist/esm/protocol/limit-io.js
 - ./node_modules/@connectrpc/connect/dist/cjs/protocol/limit-io.js
by replacing
`const maxReadMaxBytes = 0xffffffff;`
to
`const maxReadMaxBytes = 0x0fffffff;`

It's now working fine but I dont really understand maybe 32 bit system ?

**Environment (please complete the following information):**

"@connectrpc/connect": "1.3.0",
- Node.js version: 18

**Comment by srikrsna-buf** [comment]
> After a dependencies conflict that lead me to disable @bufbuild/buf (arm not compatible but look ok for this project to remove it)

`@bufbuild/buf` should be dev dependency, ideally needn't be installed where the final code is running.

> * by replacing
>   `const maxReadMaxBytes = 0xffffffff;`
>   to
>   `const maxReadMaxBytes = 0x0fffffff;`

I am guessing reducing the limit worked for you. From the stack trace, I can't figure out if it is the server or client, but both support `readMaxBytes` option. You can use that instead of editing the `node_modules` file.

> It's now working fine but I dont really understand maybe 32 bit system ?

Not sure, but I think it has something to with how `zlib` is implemented on different platforms.

**Comment by Dam63** [comment]
Hi, thanks for the info
How to use readMaxBytes option ?
I run it with :
node src/prog.js

**Comment by srikrsna-buf** [comment]
Can you show me the transport code?
